name: flutter_assignment
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  bloc: 8.1.2
  cupertino_icons: 1.0.6
  dio: 5.3.3
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_pretty_dio_logger: ^3.0.0


dev_dependencies:
  bloc_test: 9.1.5
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mocktail: 1.0.1
  mocktail_image_network: ^1.0.0
  test: 1.24.3
  very_good_analysis: 5.1.0

flutter:
  uses-material-design: true
